### ISSUE TITLE
The Master Checklist - Fall 2021

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/advgis-echo#1]
# Getting Started
- [ ] Review the [academic calendar](https://www.wm.edu/offices/registrar/calendarsandexams/ugcalendars/index.php#fall).
- [ ] Update your [ArcGIS Online](https://www.arcgis.com/index.html) (AGOL) profile to include a personalized photo or avatar and your areas of special skills (e.g., "I'm good at data vis", "I'm a StoryMap master", or "I literally know how to use Python").
- [ ] Create and/or update your [GitHub](https://github.com/) account to match your AGOL account. 
    - [ ] Includes your preferred name (so we know who you are)
    - [ ] Includes the same profile image you used for your AGOL profile (to help us know it's you)
- [ ] Introduce yourself to the class with a comment on the [Welcome Discussion](https://github.com/orgs/cga-wm/teams/echo-squad/discussions/1).
- [ ] Review the [syllabus](https://cga-wm.github.io/course/adv-gis/syllabus/index.html).
- [ ] Post a question about the syllabus to the [About the syllabus](https://github.com/cga-wm/advgis-delta/discussions/2) discussion.
- [ ] Choose a focus: __programming__ or __analysis__ (delete the one you don't want).
    - Programming focus: you already have some experience using Python, so begin your journey by looking at Notebooks, the cloud-based programming environment for solving your geospatial problems 
    - Analysis focus: you are comfortable with ArcGIS Pro and have little to no programming experience, so let's start with what you are comfortable with and learn out how to use ModelBuilder to create reproducible geospatial workflows
- [ ] Create a new issue on our repository's [Issues](https://github.com/cga-wm/advgis-delta/issues), title it with your name (e.g., Davis's Checklist), copy-and-paste [The Master Checklist](https://github.com/cga-wm/advgis-delta/issues/3) content to the "Write" section, under Assignees: assign yourself, under Labels: checklist. Be sure to note your issue's unique number.
- [ ] Join the GroupMe chat (email your professor your preferred email for GroupMe): for example, by liking the "hello, advanced GIS" comment.
- [ ] Save a copy of the [Performance Accomplishments](https://docs.google.com/document/d/1zB86jyiyrkrS2POvmFOBYu4XH0acEw-vSl4L54MDKPY/edit?usp=sharing) document and share it with your professor (with edit permissions so I can leave comments)
    - [ ] Update the Evaluee section with your name and whether you are taking this class at the undergraduate (GIS 420) or certificate (GIS 520) level (*note: there are different expectations for successful completion based on the class level*)
- [ ] Check out your professor's Zoom room (link and password to be emailed to you separately)
- [ ] Check out your professor's [Nooks community](https://nooks.in/goto/7cc0KabvZpnfVKyV?pwd=o162Tu) (this is where Office Hours are normally held; however, you can schedule a meeting at a mutually convenient time via GroupMe chat or email)
- [ ] Log into AGOL and make sure you are a member of the "AdvGIS - Spring 2021" group
- [ ] Sign up for your Semester Start meeting [here](https://docs.google.com/spreadsheets/d/1uw45_Wz3CKbZvctBNtGY2OO8JDo3pt6xA5JIp6aUgQo/edit?usp=sharing)
- [ ] Find a team (in groups of up to three people) to work together on the [client meeting](https://github.com/cga-wm/advgis-delta/issues/5).

# Weekly Engagement 
- [ ] Sign up [here](https://docs.google.com/spreadsheets/d/1E_jVgXNcqfz9a38iRQ9HTEbR6_XDoWBLtFgJKJjmxto/edit?usp=sharing) to schedule to contribute at least once to each of the five weekly topics. 
    **If you are a certificate student, instead sign up for one topic each week.**
    - [ ] Question of the week. Date(s): __________
    - [ ] Data share of the week. Date(s): __________
    - [ ] Ethics consideration of the week. Date(s): __________
    - [ ] Vocab term of the week. Date(s): __________
    - [ ] Method of the week. Date(s): __________
- [ ] Respond to and/or engage with the five weekly discussion posts. 
    If there is no natural response, then please respond with a reaction to the comment.
- [ ] Complete your weekly reports.
    - Your personalized issue link (from the new issue you created above): _______
    - Reports completed:
        - [ ] Week 1 (optional)
        - [ ] Week 2 (optional)
        - [ ] Week 3
        - [ ] Week 4
        - [ ] Week 5
        - [ ] Week 6
        - [ ] Week 7
        - [ ] Week 8
        - [ ] Week 9
        - [ ] Week 10
        - [ ] Week 11
        - [ ] Week 12
        - [ ] Week 13
        - [ ] Week 14
        - [ ] Week 15

# Become More Geoethical 
- [ ] Watch the YouTube video and follow along with the [slideshow](https://cga-wm.github.io/course/adv-gis/lectures/geoethics/#/what-are-geoethics)
- [ ] Check out [Google Takeout](https://takeout.google.com/) to see what data has been collected on you.
- [ ] Find and share an article that has a geoethical concern and share it during your week
- [ ] Listen to an episode of the [VerySpatial podcast](https://veryspatial.com/).
    - Link to episode you listed to: ___________
- [ ] Listen to one or more student examples [here](https://cga-wm.github.io/course/adv-gis/2020-08-03-podcasts-vlogs.html).
    - Episode(s) you listen to: ____________
- [ ] Research, script, and record a podcast episode on the topic of geoethics.
    Include three (3) sources or citations.
    Be sure to share the podcast on the course discussion board.

# Enhance Your Skills
- [ ] Watch the videos in the [Advanced GIS | Spring 2021](https://youtube.com/playlist?list=PLbIkNQKCuzMNp93D3wzRh8x8ceL4HKpIA) YouTube Playlist
    - [ ] Time Management 
    - [ ] Sharing on ArcGIS Online 
    - [ ] Graphical Models 
    - [ ] Introduction to Programming 
    - [ ] Introduction to Notebooks 
    - [ ] Geoprocessing 

### Managing Your Data
- [ ] Read about metadata (e.g., [here](https://cga-wm.github.io/course/intro/chapter-3-data.html#metadata))
- [ ] Organize all your items on AGOL.
    This includes updating the metadata (summary, description, terms of use, tags, and credits (attribution) appropriately.
    Come up with a plan on how you organize your AGOL content and a system for tagging your items; consider posting to the discussion board your ideas on how to best use tags.
- [ ] Create a file geodatabase for organizing your datasets (see [AGOL](https://wm-gis.maps.arcgis.com/home/item.html?id=31b93985ce284cb1876c8483cab78366#overview) item)

### [Getting Started With Notebooks](https://cga-wm.github.io/course/adv-gis/2020-10-29-getting-started-with-notebooks.html)
- [ ] [My First Notebook](https://wm-gis.maps.arcgis.com/home/item.html?id=c8cc47cf8c0f4f5aadcff34aed8b48b3)
- [ ] [Python Fundamentals](https://wm-gis.maps.arcgis.com/home/item.html?id=0be90664f6e345709832b6cc60361bff)
- [ ] [More Python Fundamentals](https://wm-gis.maps.arcgis.com/home/item.html?id=6ae79225677547978e5e86eef75cd39d)
- [ ] [Files and Folders](https://wm-gis.maps.arcgis.com/home/item.html?id=67d191b2a0a94b6ebe6cc7f1aec50c48)
- [ ] [Working With Data](https://wm-gis.maps.arcgis.com/home/item.html?id=367fcabcb8da4dac9851b7e80c246706)
- [ ] [The File Geodatabase](https://wm-gis.maps.arcgis.com/home/item.html?id=31b93985ce284cb1876c8483cab78366)
- [ ] [Geoprocessing with the ArcGIS API](https://wm-gis.maps.arcgis.com/home/item.html?id=0c4825b7e0f04fa6afba2b108eb338a4)
- [ ] [Geoprocessing with arcpy](https://wm-gis.maps.arcgis.com/home/item.html?id=d81dd1f12f574b39b248a6311c619a7b)
- [ ] [RevealJS Presentations Notebook](https://wm-gis.maps.arcgis.com/home/item.html?id=913ac54ed2fb4847a4a41cfc56a59549) (_optional_)

### Additional Practice
Complete at least six (6) [ArcGIS for Developers](https://developers.arcgis.com/documentation/) tutorials (*include names of and links to each tutorial completed).

- [ ] _Tutorial 1_
- [ ] _Tutorial 2_
- [ ] _Tutorial 3_
- [ ] _Tutorial 4_
- [ ] _Tutorial 5_
- [ ] _Tutorial 6_

# Client Meeting Project
- [ ] Form a consultancy.
    It should have: 
    * Name: 
    * Members: 
    * Logo: 
    * Slogan (optional):
- [ ] Propose a paper for approval [here](https://docs.google.com/spreadsheets/d/1H-DItUonsXgbV-mf6zfoqwroapkcPE-WwoRd7A-z7pg/edit?usp=sharing).
- [ ] Create a web presence (e.g., website) for your GIS consulting work.
    URL: 
    It should include the following:
    - [ ] Link to article you are reviewing 
    - [ ] Video (~20 min or less) that summarizes your article (background, methods, and results + your first impressions)
    - [ ] Video (~10 min or less) on data collection or creation (w/ map or visual)
    - [ ] Audio/video (~ 5 min or less) on a geoprocess or challenge you faced
    - [ ] Weekly blog (should highlight milestones, methods, updates)
    - [ ] Section on geoethics
- [ ] Prepare a publicly accessible progress report for your client meeting. 
    It may be your website, slideshow, StoryMap, or another web-accessible document.
    Be sure to include visual aids.
    Remember that your client is not a GIS expert; tone your report for a lay audience.
- [ ] Schedule a progress report meeting with your client [here](https://docs.google.com/spreadsheets/d/1P_bfKUewFq822j0oV-ZW-Sbj68QTVjEWy5Uk-xf85Y4/edit?usp=sharing).
- [ ] Write down your thoughts regarding the experience of working through this project and the client meeting.

# Midterm
- [ ] Sign up for a Progress Report meeting [here](https://docs.google.com/spreadsheets/d/1uw45_Wz3CKbZvctBNtGY2OO8JDo3pt6xA5JIp6aUgQo/edit?usp=sharing)

# Final
- [ ] Sign up for a final evaluation time [here](https://docs.google.com/spreadsheets/d/1uw45_Wz3CKbZvctBNtGY2OO8JDo3pt6xA5JIp6aUgQo/edit?usp=sharing).
- [ ] Prepare solutions to two (2) special works projects.
    _Note that the same special works project cannot be used to satisfy both of the following._
    - [ ] Create a tutorial that accomplishes the reproducibility of your methods and results
    - [ ] Complete a special works project live to your professor.
- [ ] Prepare your Performance Accomplishments document and share it with your professor.
    - [ ] _Objective 1:_ include the benefits of independent and collaborative work
    - [ ] _Objective 2:_ prepare a definition of geoethics and provide example(s) that demonstrate what it means (include all necessary citations)
    - [ ] _Objective 3:_ Highlight a skill that you learned this semester (e.g., time management, data management, programming or other); reflect on how you organized your AGOL content; and reflect on the three pitfalls of GIS:
        1. Failure to know GIS (theory and lexicon).
        1. Failure to communicate GIS (purpose, process and metadata).
        1. Failure to execute GIS (using the right data with the right tools in the right way).
    - [ ] _Objective 4:_ reflect on your client meeting, what you would have done differently, and the challenges with communicating geospatial methods to a lay audience
    - [ ] _Objective 5:_ reflect on the benefits of programmatic approaches for addressing geospatial challenges and provide an example
- [ ] Complete the course evaluation.
    Please include your thoughts on the asynchronous course structure, things that worked, and things that didn't work for you.
- [ ] Permission to use media (e.g., web content, audio or video) unrestricted for educational purposes is (**not**) granted
    *Please update appropriately and include any licenses you prefer to have associated with your materials.*
