### ISSUE TITLE
Dominic Fornatora - Master Checklist

### ISSUE THREAD

**Issue by dfornatora** [cga-wm/advgis-echo#11]
# Getting Started
- [ ] Review the [academic calendar](https://www.wm.edu/offices/registrar/calendarsandexams/ugcalendars/index.php#fall).
- [ ] Review the [syllabus](https://cga-wm.github.io/course/adv-gis/syllabus/index.html).
    - Feel free to post a question about the syllabus to the [About the syllabus](https://github.com/orgs/cga-wm/teams/echo-squad/discussions/2) discussion.
- [ ] Update your [ArcGIS Online](https://www.arcgis.com/index.html) (AGOL) profile to include a personalized photo or avatar and your areas of special skills (e.g., "I'm good at data vis", "I'm a StoryMap master", or "I literally know how to use Python").
- [ ] Create and/or update your [GitHub](https://github.com/) account. 
    - [ ] Includes your preferred name (so we know who you are)
    - [ ] Includes the same profile image you used for your AGOL profile (to help us know it's you)
- [ ] Choose a focus: __programming__ or __analysis__ (delete the one you don't want).
    - Programming focus: you already have some experience using Python, so begin your journey by looking at Notebooks, the cloud-based programming environment for solving your geospatial problems 
    - Analysis focus: you are comfortable with ArcGIS Pro and have little to no programming experience, so let's start with what you are comfortable with and learn out how to use ModelBuilder to create reproducible geospatial workflows
- [ ] Join the [GroupMe](https://groupme.com/join_group/69693978/Fe5J6QsW) chat (email your professor your preferred email for GroupMe)
    - Like a comment or just say "hi"
- [ ] Log into AGOL and make sure you are a member of the "AdvGIS - Fall 2021" group
- [ ] I completed the Ice Breaker challenge on the first day of classes

## On GitHub
- [ ] Familiarize yourself with the Markdown syntax (see resources below)
    * [Mastering Markdown - GitHub](https://guides.github.com/features/mastering-markdown/)
    * [Markdown Guide - Google Colab](https://colab.research.google.com/notebooks/markdown_guide.ipynb)
    * [Stackedit.io - In Browser Markdown Editor](https://stackedit.io/)
- [ ] Introduce yourself to the class with a comment on the [Welcome Discussion](https://github.com/orgs/cga-wm/teams/echo-squad/discussions/1).
- [ ] (*Wait until you hear from your instructor that it's okay to do this*) Create a new issue on our repository's [Issues](https://github.com/cga-wm/advgis-echo/issues), title it with your name (e.g., Davis's Checklist), copy-and-paste [The Master Checklist](https://github.com/cga-wm/advgis-echo/issues/1) content to the "Write" section, under Assignees: assign yourself, under Labels: checklist. Be sure to note your issue's unique number.
    - This is your copy of the master checklist
    - Use it to keep track of your accomplishments as you go through the semester
    - You may also see how your peers are progressing to judge your own time management
- [ ] Create your Report Wiki on our repository's [Wiki page](https://github.com/cga-wm/advgis-echo/wiki)
    - This is where you submit your weekly tasks, goals, and accomplishments
    - See Home page for instructions

## For Certificate Students only
- [ ] Save a copy of the [Performance Accomplishments](https://docs.google.com/document/d/1Vry97f0mC9Qi9V-Wt41zYsPV9jRo1DIsTGN1dhH2oC8/edit?usp=sharing) document and share it with your professor (with edit permissions so I can leave comments)
    - Update the Evaluee section with your name
- [ ] Sign up for your Semester Start, Progress, and Final meetings [here](https://docs.google.com/spreadsheets/d/1kv8LPCiDE9u-cu4gYRv5q9OsniGa8btOIAqOhGLMFi8/edit?usp=sharing)
    - *Note that you can adjust your scheduled times at any time; please inform your instructor of any changes.*

# The Consultancy
- [ ] Find a team (in groups of up to three people) to work together 
- [ ] Form your consultancy.
    It should have: 
    - [ ] Name: 
    - [ ] Members: 
    - [ ] Logo: 
    - [ ] Slogan:
- Create a publicly accessible website and provide the following:
    - [ ] Site URL: 
    - Your site should include at least the following:
        - [ ] Overview page (who we are / what we do)
        - [ ] Blog page (should be updated at least weekly including milestones, methods and other relevant updates)
        - [ ] Geoethics section / page (define geoethics and how you apply it to your work)
- [ ] Add your consultancy group details [here](https://docs.google.com/spreadsheets/d/1tg80NOT54_Ze2Ld3gRi4nEe57_KCs1cH9hSPgZ_1K7k/edit?usp=sharing).

## The Reproducibility Project and Client Meeting
- [ ] Propose a paper for approval [here](https://docs.google.com/spreadsheets/d/1tg80NOT54_Ze2Ld3gRi4nEe57_KCs1cH9hSPgZ_1K7k/edit?usp=sharing).
- Update your website with the following:
    - [ ] Link to article you are reviewing 
    - [ ] Video (~20 min or less) that summarizes your article (background, methods, and results + your first impressions)
    - [ ] Video (~10 min or less) on data collection or creation (w/ map or visual)
    - [ ] Audio/video (~ 5 min or less) on a geoprocess or challenge you faced
- [ ] Prepare a publicly accessible progress report for your client meeting
    - It may be your website, slideshow, StoryMap, or another web-accessible document. Make it clear on your website how  / where to access it.
    - Be sure to include visual aids
    - Remember that your client is not a GIS expert; tone your report for a lay audience
- [ ] Schedule a progress report meeting with your client [here](https://docs.google.com/spreadsheets/d/18rArUjK1Yq-Td0zPV9sLlIH4h9k0C4euAnDD3ljlhhI/edit?usp=sharing)
- [ ] Write down your thoughts regarding the experience of working through this project and the client meeting in your weekly report
    - Copy and paste your response here:
- [ ] Rate your paper's level of reproducibility (based on your opinion)
    - The levels are:
        - **S**: satisfactory (methods are clear and reproducible)
        - **M**: marginal (it is hard to say because some methods are unclear and/or data are outdated or not readily available)
        - **U**: unsatisfactory (there is no known way to reproduce these methods)
    - Our consultancy gives our paper the rating of _____ for the following reasons:

## The Special Works Solutions
- Prepare two methodologies for solving one of the special works projects
    - The special works project should emphasize a skill set that one of the consultants identified as a weakness in the pre-semester survey
    - Solutions may be typed or recorded
- Solution Method 1: 
    - [ ] Solved to "basic" level
    - [ ] Solved to "intermediate" level (tick both boxes)
- Solution Method 2: 
    - [ ] Solved to "basic" level
    - [ ] Solved to "intermediate" level (tick both boxes)
- [ ] We posted our solutions to our consultancy website
- [ ] We presented a discussion of our solutions in class or on GitHub

## The Novel Datasets
- [ ] Our consultancy created a novel dataset
    - [ ] in a file geodatabase and/or
    - [ ] in GeoJSON format
- [ ] We posted a link to our dataset (with a license, description, and relevant metadata) to our consultancy website
- [ ] We presented a discussion of our dataset (and the methods for its creation) in class or on GitHub

# Engagement 
- [ ] Sign up [here](https://docs.google.com/spreadsheets/d/1_s_BHjU_0AUkzKyrgEiL-YqQzHp_CI8miEg5EkQoMpg/edit?usp=sharing) to schedule to contribute at least once to each of the five weekly topics. 
    **If you are a certificate student, instead sign up for one topic each week.**
    - [ ] Question of the week. Date(s): __________
    - [ ] Data share of the week. Date(s): __________
    - [ ] Ethics consideration of the week. Date(s): __________
    - [ ] Vocab term of the week. Date(s): __________
    - [ ] Method of the week. Date(s): __________
- [ ] Each week, respond to and/or engage with the five weekly discussion posts. 
    If there is no natural response, then please respond with a reaction to the comment.
    - [ ] I responded to more than five discussion posts on GitHub
    - [ ] I responded to more than ten discussion posts on GitHub
- [ ] Complete your weekly reports.
    - Your personalized issue link (from the new issue you created above): _______
    - Reports completed:
        - [ ] Week 1 (optional)
        - [ ] Week 2 (optional)
        - [ ] Week 3
        - [ ] Week 4
        - [ ] Week 5
        - [ ] Week 6
        - [ ] Week 7
        - [ ] Week 8
        - [ ] Week 9
        - [ ] Week 10
        - [ ] Week 11
        - [ ] Week 12
        - [ ] Week 13
        - [ ] Week 14
        - [ ] Week 15
- [ ] Share a selfie where you are holding or standing next to a physical item within Swem library (e.g., an open book, a painting, or a map) to our GitHub discussion board with a short description of the item and how it relates to a geospatial topic

# Become More Geoethical 
- [ ] Listen to the lecture on [Geoethics](https://cga-wm.github.io/course/adv-gis/lectures/geoethics/#/what-are-geoethics)
- [ ] Complete the [Google Takeout](https://takeout.google.com/) challenge
- [ ] Find and share an article that has a geoethical concern and share it during your discussion topic week
- [ ] Listen to an episode of the [VerySpatial podcast](https://veryspatial.com/); use the search bar to filter results for "ethics" or other ethical term, phrase or idea
    - Link to episode you listed to: ___________
    - [ ] I shared a discussion on ________ that summarizes the ethics topic in the podcast linked above in class or on GitHub
- [ ] Listen to one or more student examples [here](https://cga-wm.github.io/course/adv-gis/2020-08-03-podcasts-vlogs.html).
    - [ ] I shared a discussion on _________ that summarizes the podcast(s) ___________ in class or on GitHub
- [ ] Research, script, and record a podcast episode on the topic of geoethics, including at least three (3) sources or citations
    - [ ] Share your podcast

### Managing Your Data
- [ ] I read about metadata (e.g., [here](https://cga-wm.github.io/course/intro/chapter-3-data.html#metadata))
- [ ] I organized the items I own on AGOL.
    - [ ] This includes creating folders and/or updating item names
    - [ ] This includes updating the metadata (summary, description, terms of use, tags, and credits (attribution) appropriately on all shared items (organizationally, publicly or with groups)
    - [ ] I shared a plan on how I organize my AGOL content and/or a system for tagging items in class or on GitHub

### [Getting Started With Notebooks](https://cga-wm.github.io/course/adv-gis/2020-10-29-getting-started-with-notebooks.html)
- [ ] [My First Notebook](https://wm-gis.maps.arcgis.com/home/item.html?id=c8cc47cf8c0f4f5aadcff34aed8b48b3)
- [ ] [Python Fundamentals](https://wm-gis.maps.arcgis.com/home/item.html?id=0be90664f6e345709832b6cc60361bff)
- [ ] [More Python Fundamentals](https://wm-gis.maps.arcgis.com/home/item.html?id=6ae79225677547978e5e86eef75cd39d)
- [ ] [Files and Folders](https://wm-gis.maps.arcgis.com/home/item.html?id=67d191b2a0a94b6ebe6cc7f1aec50c48)
- [ ] [Working With Data](https://wm-gis.maps.arcgis.com/home/item.html?id=367fcabcb8da4dac9851b7e80c246706)
- [ ] [The File Geodatabase](https://wm-gis.maps.arcgis.com/home/item.html?id=31b93985ce284cb1876c8483cab78366)
- [ ] [Geoprocessing with the ArcGIS API](https://wm-gis.maps.arcgis.com/home/item.html?id=0c4825b7e0f04fa6afba2b108eb338a4)
- [ ] [Geoprocessing with arcpy](https://wm-gis.maps.arcgis.com/home/item.html?id=d81dd1f12f574b39b248a6311c619a7b)
- [ ] [RevealJS Presentations Notebook](https://wm-gis.maps.arcgis.com/home/item.html?id=913ac54ed2fb4847a4a41cfc56a59549) (_optional_)

### Additional Practice
Complete at least three (3) hours or six (6) tutorials from one of the following sites: (1) [Esri Academy](https://www.esri.com/training/arcgis-online-training/); (2) [ArcGIS Developer Guides](https://developers.arcgis.com/documentation/); (3) [Learn ArcGIS](https://learn-arcgis-learngis.hub.arcgis.com/); (4) other approved resource (*include names of and links to each tutorial completed) 

- [ ] _Tutorial 1_
- [ ] _Tutorial 2_
- [ ] _Tutorial 3_
- [ ] _Tutorial 4_
- [ ] _Tutorial 5_
- [ ] _Tutorial 6_

# Final Touches
- [ ] I updated this checklist to match my accomplishments (*you are not required to complete everything on this checklist*)
- [ ] I completed the course evaluation
    - Please include your thoughts on the course structure, topics, things that worked, and things that didn't work for you
- [ ] I am signed up for the CGA listserve
    - The link is available on the CGA [homepage](https://www.wm.edu/as/cga/)
- [ ] I grant unrestricted permission to use media (e.g., web content, audio or video) I created for educational purposes
    *Note that you are not required to tick this box and, at any time, you may request that materials you made for this class be removed from use in past, current, and future classes*

## For certificate students only
- Prepare solutions to two (2) special works projects.
    _Note that the same special works project cannot be used to satisfy both of the following._
    - [ ] Create a tutorial (written, audio, video) that accomplishes the reproducibility of your methods and results
    - [ ] Complete a live demonstration of solving a special works project.
- Prepare your Performance Accomplishments document and share it with your professor.
    - [ ] _Objective 1:_ include the benefits of independent and collaborative work
    - [ ] _Objective 2:_ prepare a definition of geoethics and provide example(s) that demonstrate what it means (include all necessary citations)
    - [ ] _Objective 3:_ Highlight a skill that you learned this semester (e.g., time management, data management, programming or other); reflect on how you organized your AGOL content; and reflect on the three pitfalls of GIS:
        1. Failure to know GIS (theory and lexicon).
        1. Failure to communicate GIS (purpose, process and metadata).
        1. Failure to execute GIS (using the right data with the right tools in the right way).
    - [ ] _Objective 4:_ reflect on your client meeting, what you would have done differently, and the challenges with communicating geospatial methods to a lay audience
    - [ ] _Objective 5:_ reflect on the benefits of programmatic approaches for addressing geospatial challenges and provide an example
